services:

  db:
    container_name: go-project-db
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - internal
    ports:
      - 3306:3306

  adminer:
    container_name: go-project-adminer
    image: adminer
    networks:
      - internal
    ports:
      - 8080:8080

volumes:
  mysql:

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.221.0/28